import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} relative font-inter antialiased`}>
        {children}
        <footer className="absolute bottom-4 left-6 right-6 text-center md:bottom-8 md:left-12 md:right-auto md:text-left">
          <a
            className="text-xs text-slate-500 hover:underline"
            href="https://cruip.com"
          >
            &copy;Cruip - Tailwind CSS templates
          </a>
        </footer>
      </body>
    </html>
  );
}
